runtime: python39
service: backend
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  PYTHON_ENV: "production"

handlers:
- url: /.*
  script: auto
  secure: always
